#!/usr/bin/env python3
"""
AgentProc bridge for the `kimi` CLI (Kimi Code CLI).

Invokes:
    kimi --print -p <message> --output-format=stream-json \
        --session <session_id> \
        [--model <model>]

kimi's --print mode emits role-based NDJSON on stdout:
    role=assistant  → streaming text or final reply
    role=tool       → tool result (not forwarded to user)

Session management: the bridge generates a UUID on the first turn and uses it
as the kimi --session id. The UUID is forwarded via AGENT_SESSION: so the SDK
can pass it back on subsequent turns via AGENT_SESSION_ID.

Env vars:
    AGENT_MESSAGE          User message
    AGENT_SESSION_ID       Previous session id (empty = new session)
    AGENT_STREAMING        "1" streaming mode, "0" one-shot
    KIMI_MODEL             Optional model override
    KIMI_TIMEOUT           Process timeout in seconds (default 600)
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import uuid
from typing import Optional

_HUB_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _HUB_DIR not in sys.path:
    sys.path.insert(0, _HUB_DIR)

from _shared.stream_utils import EventResult, run_bridge  # noqa: E402


CLI_NAME = "kimi"
INSTALL_HINT = "See https://moonshotai.github.io/kimi-cli for installation"

# Module-level storage for the session ID generated by build_args.
# parse_event returns it so stream_utils can emit AGENT_SESSION:.
_session: dict = {"id": None}


def build_args(message: str, session_id: str, env) -> list[str]:
    sid = session_id or str(uuid.uuid4())
    _session["id"] = sid
    args = [
        CLI_NAME, "--print", "-p", message,
        "--output-format=stream-json",
        "--session", sid,
    ]
    model = env.get("KIMI_MODEL", "").strip()
    if model:
        args += ["--model", model]
    return args


def parse_event(event: dict) -> Optional[EventResult]:
    role = event.get("role")
    if role == "assistant":
        content = event.get("content") or ""
        if content:
            return EventResult(
                partial_text=content,
                final_text=content,
                session_id=_session["id"],
            )
    return None


if __name__ == "__main__":
    try:
        sys.exit(run_bridge(CLI_NAME, INSTALL_HINT, build_args, parse_event))
    except BrokenPipeError:
        sys.exit(1)
