#!/usr/bin/env node
'use strict';
/**
 * AgentProc bridge for the `kimi` CLI (Kimi Code CLI).
 *
 * Invokes:
 *   kimi --print -p <message> --output-format=stream-json \
 *       --session <session_id> [--model <model>]
 *
 * kimi emits role-based NDJSON events:
 *   role=assistant  → streaming text / reply body
 *   role=tool       → ignored (tool results not shown to user)
 *
 * Session management: generates a UUID on the first turn and forwards it
 * as {"type":"session"}. Subsequent turns use --session <id> to resume.
 */

const crypto = require('node:crypto');
const path = require('node:path');
const HUB_DIR = path.resolve(__dirname, '..');
const { runBridge } = require(path.join(HUB_DIR, '_shared', 'stream_utils.js'));

const CLI_NAME = 'kimi';
const INSTALL_HINT = 'See https://moonshotai.github.io/kimi-cli for installation';

// Module-level storage for the session ID generated by buildArgs.
// parseEvent returns it so runBridge can emit {"type":"session"}.
const session = { id: null };

function buildArgs(message, sessionId, env) {
  session.id = sessionId || crypto.randomUUID();
  const args = [
    CLI_NAME, '--print', '-p', message,
    '--output-format=stream-json',
    '--session', session.id,
  ];
  const model = (env.KIMI_MODEL || '').trim();
  if (model) {
    args.push('--model', model);
  }
  return args;
}

function parseEvent(event) {
  if (event.role === 'assistant') {
    const content = event.content || '';
    if (content) {
      return {
        partialText: content,
        finalText: content,
        sessionId: session.id,
      };
    }
  }
  return null;
}

runBridge({ cliName: CLI_NAME, cliInstallHint: INSTALL_HINT, buildArgs, parseEvent }).catch(e => {
  process.stderr.write(`[kimi-code bridge] unhandled error: ${e && (e.stack || e)}\n`);
  process.exit(1);
});
